// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define([], function() {
    var util;
    return util = {
      platformInfo: {
        isChrome: true,
        isFirefox: false
      },
      canvas: function(size, styles) {
        var canvas;
        canvas = document.createElement('canvas');
        canvas.width = size.width;
        canvas.height = size.height;
        this.apply(canvas.style, styles);
        this.setImageRendering(canvas);
        return canvas;
      },
      apply: function(dest, src) {
        var key, value;
        for (key in src) {
          if (!__hasProp.call(src, key)) continue;
          value = src[key];
          dest[key] = value;
        }
        return dest;
      },
      setImageRendering: function(el) {
        var rendering;
        rendering = 'optimizeSpeed';
        if (this.platformInfo.isChrome) {
          rendering = '-webkit-optimize-contrast';
        } else if (this.platformInfo.isFirefox) {
          rendering = '-moz-crisp-edges';
        }
        el.style.imageRendering = rendering;
        return el;
      }
    };
  });

}).call(this);
